# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: volt_guard.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='volt_guard.proto',
  package='voltguard',
  syntax='proto3',
  serialized_pb=_b('\n\x10volt_guard.proto\x12\tvoltguard\"+\n\tPowerMode\x12\x0c\n\x04mode\x18\x01 \x01(\r\x12\x10\n\x08power_mw\x18\x02 \x01(\r\".\n\x0cModeResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"\\\n\nSensorData\x12\x14\n\x0ctemp_celsius\x18\x01 \x01(\x05\x12\x12\n\nvoltage_mv\x18\x02 \x01(\r\x12\x12\n\ncurrent_ma\x18\x03 \x01(\r\x12\x10\n\x08power_mw\x18\x04 \x01(\r\"\x07\n\x05\x45mpty\"1\n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t2\xf5\x01\n\tVoltGuard\x12=\n\x0cSetPowerMode\x12\x14.voltguard.PowerMode\x1a\x17.voltguard.ModeResponse\x12\x36\n\x0cGetPowerMode\x12\x10.voltguard.Empty\x1a\x14.voltguard.PowerMode\x12\x35\n\nGetSensors\x12\x10.voltguard.Empty\x1a\x15.voltguard.SensorData\x12:\n\x0bHealthCheck\x12\x10.voltguard.Empty\x1a\x19.voltguard.HealthResponseb\x06proto3')
)




_POWERMODE = _descriptor.Descriptor(
  name='PowerMode',
  full_name='voltguard.PowerMode',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mode', full_name='voltguard.PowerMode.mode', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='power_mw', full_name='voltguard.PowerMode.power_mw', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=74,
)


_MODERESPONSE = _descriptor.Descriptor(
  name='ModeResponse',
  full_name='voltguard.ModeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='voltguard.ModeResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='voltguard.ModeResponse.error', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=122,
)


_SENSORDATA = _descriptor.Descriptor(
  name='SensorData',
  full_name='voltguard.SensorData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='temp_celsius', full_name='voltguard.SensorData.temp_celsius', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='voltage_mv', full_name='voltguard.SensorData.voltage_mv', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='current_ma', full_name='voltguard.SensorData.current_ma', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='power_mw', full_name='voltguard.SensorData.power_mw', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=124,
  serialized_end=216,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='voltguard.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=218,
  serialized_end=225,
)


_HEALTHRESPONSE = _descriptor.Descriptor(
  name='HealthResponse',
  full_name='voltguard.HealthResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='voltguard.HealthResponse.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='version', full_name='voltguard.HealthResponse.version', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=227,
  serialized_end=276,
)

DESCRIPTOR.message_types_by_name['PowerMode'] = _POWERMODE
DESCRIPTOR.message_types_by_name['ModeResponse'] = _MODERESPONSE
DESCRIPTOR.message_types_by_name['SensorData'] = _SENSORDATA
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['HealthResponse'] = _HEALTHRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PowerMode = _reflection.GeneratedProtocolMessageType('PowerMode', (_message.Message,), dict(
  DESCRIPTOR = _POWERMODE,
  __module__ = 'volt_guard_pb2'
  # @@protoc_insertion_point(class_scope:voltguard.PowerMode)
  ))
_sym_db.RegisterMessage(PowerMode)

ModeResponse = _reflection.GeneratedProtocolMessageType('ModeResponse', (_message.Message,), dict(
  DESCRIPTOR = _MODERESPONSE,
  __module__ = 'volt_guard_pb2'
  # @@protoc_insertion_point(class_scope:voltguard.ModeResponse)
  ))
_sym_db.RegisterMessage(ModeResponse)

SensorData = _reflection.GeneratedProtocolMessageType('SensorData', (_message.Message,), dict(
  DESCRIPTOR = _SENSORDATA,
  __module__ = 'volt_guard_pb2'
  # @@protoc_insertion_point(class_scope:voltguard.SensorData)
  ))
_sym_db.RegisterMessage(SensorData)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), dict(
  DESCRIPTOR = _EMPTY,
  __module__ = 'volt_guard_pb2'
  # @@protoc_insertion_point(class_scope:voltguard.Empty)
  ))
_sym_db.RegisterMessage(Empty)

HealthResponse = _reflection.GeneratedProtocolMessageType('HealthResponse', (_message.Message,), dict(
  DESCRIPTOR = _HEALTHRESPONSE,
  __module__ = 'volt_guard_pb2'
  # @@protoc_insertion_point(class_scope:voltguard.HealthResponse)
  ))
_sym_db.RegisterMessage(HealthResponse)



_VOLTGUARD = _descriptor.ServiceDescriptor(
  name='VoltGuard',
  full_name='voltguard.VoltGuard',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=279,
  serialized_end=524,
  methods=[
  _descriptor.MethodDescriptor(
    name='SetPowerMode',
    full_name='voltguard.VoltGuard.SetPowerMode',
    index=0,
    containing_service=None,
    input_type=_POWERMODE,
    output_type=_MODERESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetPowerMode',
    full_name='voltguard.VoltGuard.GetPowerMode',
    index=1,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_POWERMODE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetSensors',
    full_name='voltguard.VoltGuard.GetSensors',
    index=2,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_SENSORDATA,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='HealthCheck',
    full_name='voltguard.VoltGuard.HealthCheck',
    index=3,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_HEALTHRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_VOLTGUARD)

DESCRIPTOR.services_by_name['VoltGuard'] = _VOLTGUARD

# @@protoc_insertion_point(module_scope)
