# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from src.client import volt_guard_pb2 as volt__guard__pb2


class VoltGuardStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SetPowerMode = channel.unary_unary(
        '/voltguard.VoltGuard/SetPowerMode',
        request_serializer=volt__guard__pb2.PowerMode.SerializeToString,
        response_deserializer=volt__guard__pb2.ModeResponse.FromString,
        )
    self.GetPowerMode = channel.unary_unary(
        '/voltguard.VoltGuard/GetPowerMode',
        request_serializer=volt__guard__pb2.Empty.SerializeToString,
        response_deserializer=volt__guard__pb2.PowerMode.FromString,
        )
    self.GetSensors = channel.unary_unary(
        '/voltguard.VoltGuard/GetSensors',
        request_serializer=volt__guard__pb2.Empty.SerializeToString,
        response_deserializer=volt__guard__pb2.SensorData.FromString,
        )
    self.HealthCheck = channel.unary_unary(
        '/voltguard.VoltGuard/HealthCheck',
        request_serializer=volt__guard__pb2.Empty.SerializeToString,
        response_deserializer=volt__guard__pb2.HealthResponse.FromString,
        )


class VoltGuardServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SetPowerMode(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetPowerMode(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetSensors(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def HealthCheck(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_VoltGuardServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SetPowerMode': grpc.unary_unary_rpc_method_handler(
          servicer.SetPowerMode,
          request_deserializer=volt__guard__pb2.PowerMode.FromString,
          response_serializer=volt__guard__pb2.ModeResponse.SerializeToString,
      ),
      'GetPowerMode': grpc.unary_unary_rpc_method_handler(
          servicer.GetPowerMode,
          request_deserializer=volt__guard__pb2.Empty.FromString,
          response_serializer=volt__guard__pb2.PowerMode.SerializeToString,
      ),
      'GetSensors': grpc.unary_unary_rpc_method_handler(
          servicer.GetSensors,
          request_deserializer=volt__guard__pb2.Empty.FromString,
          response_serializer=volt__guard__pb2.SensorData.SerializeToString,
      ),
      'HealthCheck': grpc.unary_unary_rpc_method_handler(
          servicer.HealthCheck,
          request_deserializer=volt__guard__pb2.Empty.FromString,
          response_serializer=volt__guard__pb2.HealthResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'voltguard.VoltGuard', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
